language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: mcIhbwQh/y8feLhbPpXZQe1W79End8IRwE0w/Tz1w93vE7aLxf/4y/QBNnYcRtDjEYh+A8A9wvB8oCeA77vc/S0T+cxDgYDm/+3BCHU8HolrxieC0iNAOitSBjqXxbYPqJN9Zu6pBqSWGLwZGzn0YzFtz7UlGXyNB/gNu+OhFWt5QwA1y3WvWbYwdsBF1bSNxd79zngIS++QQWKNpDAToCtvnLm217vTjRx19DQeVExQ3jXWp/OD8qqpiTbD5vMATcHzqUHgMUxL5bD4ACvYtQch93G7aVIb6BKfVazxW4If3Q+0o/XPBk9dN2/KjLdtypz96pmkXPVZExYlq9sAz/2MCiqZcF1+ipg68vEySBHr6GaEv//6EmMmNiaFikvsgFfxA7XL+26djRMRwQ/Fg2omJEzrOtT/DllBuuWHDhD0Mwq05XMLoHyTpd4XUthw4sHxrM1huDKFIavmM8Ue0sfY3Ox5ba8fm92fuC581UUX8vLBxGhz6iMGaewyCjvdekljioMAzteXsqMNNSIHVMEWtqHBfutUqPJusHjzHBHGnt4v7fj7c58bosmXeoMY2tiRyorWN8orx12jaQAqSNnhOZ8PB9dJxFpIDoFVKNA0fjUH7Q01gncq0BlGCYN/X4s5cH2o7LXNt+zuvJ7CwUwjM1vF7jNiI1GncN/xkrE=
  app: scheddy
  on:
    repo: doppleware/scheddy-ui
